package creator;

import java.util.ArrayList;
import java.util.List;

import models.characters.Breed;
import models.characters.Character;

import utils.input.Getters;
import utils.input.Menu;
import utils.ui.Prettier;
import utils.ui.Ansi;

import utils.rng.StatsBudget;
import utils.rng.StatsBudget.Result;
import utils.rng.StatsBudget.ScaledLimits;

/**
 * Gestor de creació de personatges.
 *
 * <p>
 * Aquesta classe centralitza la lògica per crear una instància de
 * {@link Character}
 * demanant dades per consola. Permet dues vies de generació:
 * </p>
 * <ul>
 * <li><b>Automàtica</b>: reparteix els punts d'estadístiques i assigna una raça
 * mitjançant {@link StatsBudget}.</li>
 * <li><b>Manual</b>: l'usuari tria la raça i reparteix exactament
 * {@value #TOTAL_POINTS} punts entre 7 estadístiques.</li>
 * </ul>
 *
 * <p>
 * <b>Nota:</b> Aquesta classe és utilitària (no instanciable) i només exposa
 * mètodes estàtics.
 * </p>
 */
public class CharacterCreator {

    /**
     * Constructor privat per evitar instàncies.
     */
    private CharacterCreator() {
    }

    /**
     * Utilitat d'entrada per llegir valors des de consola amb validació.
     */
    private static final Getters getter = new Getters();

    /** Longitud mínima del nom del personatge. */
    private static final int MIN_NAME_LEN = 3;

    /** Longitud màxima del nom del personatge. */
    private static final int MAX_NAME_LEN = 20;

    /** Edat mínima permesa del personatge. */
    private static final int MIN_AGE = 12;

    /**
     * Edat màxima permesa del personatge.
     * <p>
     * En aquest cas s'accepta qualsevol enter positiu fins al límit d'Integer.
     * </p>
     */
    private static final int MAX_AGE = Integer.MAX_VALUE;

    /**
     * Pressupost total de punts per repartir entre les 7 estadístiques.
     * <p>
     * En mode manual, la suma ha de ser exactament aquest valor.
     * </p>
     */
    private static final int TOTAL_POINTS = 140;

    private static final ScaledLimits limits = StatsBudget.scaleLimits(TOTAL_POINTS);
    private static final int MIN_STAT = limits.minValue();
    private static final int MAX_STAT = limits.maxValue();

    /**
     * Restricció mínima específica per a Constitució (vida).
     * <p>
     * Es força un mínim superior al de la resta d'estadístiques.
     * </p>
     */
    private static final int MIN_CONSTITUTION = MIN_STAT + 2;

    /**
     * Llista de noms de races disponibles, obtinguda des de {@link Breed}.
     * <p>
     * Es fa servir per mostrar el menú a l'usuari en la generació manual.
     * </p>
     */
    private static final List<String> breeds = Breed.getNamesList();

    /**
     * Crea un nou personatge preguntant a l'usuari el nom i l'edat, i permetent
     * decidir si la generació d'estadístiques i raça serà automàtica o manual.
     *
     * @return una nova instància de {@link Character} amb nom, edat, estadístiques
     *         i raça.
     */
    public static Character createNewCharacter() {
        String name = getName();

        int age = getter.getInteger(
                "Si us plau, introdueixi l'edat del seu personatge: ",
                "L'edat",
                MIN_AGE,
                MAX_AGE);

        boolean autoGenerate = getter.getBoolean("Vol generar el personatge automàticament? [S/N] ", true, "S", "N");

        Generation gen = autoGenerate ? autoGenerate() : manualGenerate();

        if (autoGenerate) {
            printAutoGeneratedSummary(gen);
            Menu.pause();
        }

        return new Character(name, age, gen.stats(), gen.breed());
    }

    private static int id = 1;

    public static Character createDebugCharacter() {
        String name = "test" + id++;
        int age = 12;
        Generation gen = autoGenerate();
        return new Character(name, age, gen.stats(), gen.breed());
    }

    /**
     * Registre intern que encapsula el resultat d'una generació:
     * el paquet d'estadístiques (ordre fix) i la raça.
     *
     * <p>
     * L'ordre de {@code stats} és:
     * Força, Destresa, Constitució, Intel·ligència, Saviesa, Carisma, Sort.
     * </p>
     *
     * @param stats array d'enters amb les 7 estadístiques
     * @param breed raça seleccionada o generada
     */
    private record Generation(int[] stats, Breed breed) {
    }

    /**
     * Generació automàtica del personatge.
     *
     * <p>
     * Fa servir {@link StatsBudget#generate(int)} per repartir
     * {@value #TOTAL_POINTS}
     * i recuperar:
     * </p>
     * <ul>
     * <li>les estadístiques base</li>
     * <li>la raça associada al resultat</li>
     * </ul>
     *
     * @return un {@link Generation} amb estadístiques i raça generades
     *         automàticament
     */
    private static Generation autoGenerate() {
        Result res = StatsBudget.generate(TOTAL_POINTS);
        return new Generation(res.baseStats(), res.breed());
    }

    /**
     * Generació manual del personatge.
     *
     * <p>
     * Flux:
     * </p>
     * <ol>
     * <li>Tria de raça mitjançant un menú.</li>
     * <li>Repartiment manual de punts en 7 estadístiques, amb restriccions
     * mínimes.</li>
     * <li>Validació estricta: la suma ha de ser exactament
     * {@value #TOTAL_POINTS}.</li>
     * </ol>
     *
     * <p>
     * Si la suma no és correcta, es mostra un avís i es torna a demanar tot el
     * repartiment.
     * </p>
     *
     * @return un {@link Generation} amb estadístiques i raça escollides manualment
     */
    private static Generation manualGenerate() {
        // 1) Raça
        int breedIdx = Menu.getOption(breeds, "Tria una raça:") - 1;
        Breed breed = Breed.values()[breedIdx];

        // 2) Stats manuals (forcem suma TOTAL_POINTS)
        while (true) {
            System.out.println("\nReparteix " + TOTAL_POINTS + " punts en 7 estadístiques.");
            System.out.println("Mínim per estadística: " + MIN_STAT + " | Constitució mínim: " + MIN_CONSTITUTION);

            int strength = getter.getInteger("Força: ", "La força", MIN_STAT, MAX_STAT);
            int dexterity = getter.getInteger("Destresa: ", "La destresa", MIN_STAT, MAX_STAT);
            int constitution = getter.getInteger("Constitució (vida): ", "La constitució", MIN_CONSTITUTION,
                    MAX_STAT);
            int intelligence = getter.getInteger("Intel·ligència: ", "L'intel·ligència", MIN_STAT, MAX_STAT);
            int wisdom = getter.getInteger("Saviesa: ", "La saviesa", MIN_STAT, MAX_STAT);
            int charisma = getter.getInteger("Carisma: ", "El carisma", MIN_STAT, MAX_STAT);
            int luck = getter.getInteger("Sort: ", "La sort", MIN_STAT, MAX_STAT);

            int sum = strength + dexterity + constitution + intelligence + wisdom + charisma + luck;

            if (sum != TOTAL_POINTS) {
                Prettier.warn("La suma ha de ser exactament " + TOTAL_POINTS + ". Suma actual: " + sum);
                Menu.pause();
                continue;
            }

            int[] stats = new int[] {
                    strength, dexterity, constitution,
                    intelligence, wisdom, charisma, luck
            };

            return new Generation(stats, breed);
        }
    }

    private static String getName() {
        boolean loop = true;
        String name = "";

        while (loop) {
            name = getter.getString(
                    "Si us plau, introdueixi el nom del seu personatge: ",
                    "El nom",
                    MIN_NAME_LEN,
                    MAX_NAME_LEN);

            try {
                Integer.parseInt(name);
                Prettier.warn("El nom no pot ser un nombre. Si us plau, torni a intentar-ho.");
            } catch (NumberFormatException e) {
                loop = false;
            }
        }

        return name;
    }

    private static void printAutoGeneratedSummary(Generation gen) {
        int[] stats = gen.stats();
        Breed breed = gen.breed();

        StringBuilder sb = new StringBuilder(512);

        sb.append('\n');

        sb.append(" ")
                .append(Ansi.WHITE).append(Ansi.BOLD).append("Raça: ").append(Ansi.RESET)
                .append(Ansi.CYAN).append(Ansi.BOLD).append(breed.getName()).append(Ansi.RESET)
                .append('\n');

        String desc = (breed.getDescription() == null) ? "" : breed.getDescription().trim();
        if (!desc.isEmpty()) {
            for (String line : wrap(desc, 78)) {
                sb.append("   ")
                        .append(Ansi.DARK_GRAY).append(line).append(Ansi.RESET)
                        .append('\n');
            }
        }

        int bonusPct = (int) Math.round(breed.bonus() * 100.0);

        sb.append("   ")
                .append(Ansi.GREEN).append("Bonus: ").append(Ansi.RESET)
                .append(Ansi.BOLD).append("+").append(bonusPct).append("%").append(Ansi.RESET)
                .append(Ansi.DARK_GRAY).append(" a ").append(Ansi.RESET)
                .append(Ansi.BOLD).append(breed.bonusStat().getName()).append(Ansi.RESET)
                .append('\n');

        sb.append(" ")
                .append(Ansi.DARK_GRAY)
                .append("────────────────────────────────────────────────────────")
                .append(Ansi.RESET)
                .append('\n');

        sb.append("   ")
                .append(statChip("Força", stats[0])).append("   ")
                .append(statChip("Destresa", stats[1])).append("   ")
                .append(statChip("Constitució", stats[2])).append("   ")
                .append(statChip("Intel·ligència", stats[3]))
                .append('\n');

        sb.append("   ")
                .append(statChip("Saviesa", stats[4])).append("   ")
                .append(statChip("Carisma", stats[5])).append("   ")
                .append(statChip("Sort", stats[6]))
                .append('\n');

        sb.append(" ")
                .append(Ansi.DARK_GRAY)
                .append("────────────────────────────────────────────────────────")
                .append(Ansi.RESET)
                .append('\n');

        System.out.print(sb.toString());
    }

    private static String statChip(String label, int value) {
        return Ansi.DARK_GRAY + label + ":" + Ansi.RESET + " " + Ansi.BOLD + value + Ansi.RESET;
    }

    private static List<String> wrap(String text, int maxWidth) {
        text = (text == null) ? "" : text.trim();
        if (text.isEmpty())
            return List.of();
        if (text.length() <= maxWidth)
            return List.of(text);

        ArrayList<String> lines = new ArrayList<>();
        String[] words = text.split("\\s+");
        StringBuilder line = new StringBuilder();

        for (String w : words) {
            if (line.isEmpty()) {
                line.append(w);
            } else if (line.length() + 1 + w.length() <= maxWidth) {
                line.append(' ').append(w);
            } else {
                lines.add(line.toString());
                line.setLength(0);
                line.append(w);
            }
        }
        if (!line.isEmpty())
            lines.add(line.toString());
        return lines;
    }
}